echo "Displaying Positional Parameters"
echo "File name  : $0"
echo "Argument 1 : $1"
echo "Argument 2 : $2"
echo "Argument 3 : $3"
echo "Number of Args : $#"
echo "Given Text : $@"
echo "Argument 4 : $*"
echo "ID of the process : $$"
